using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using MongoDB.Driver;
using MongoDB.Framework.Mapping.Types;

namespace MongoDB.Framework.Mapping
{
    public class IdMap : MemberMap
    {
        public IdMap()
        {
            this.Key = "_id";
            this.ValueType = new IdValueType();
        }

        public override void  MapToDocument(object entity, Document document)
        {
            base.MapToDocument(entity, document);

            //we don't want an empty _id because it should be autogenerated if it doesn't exist.
            if (document[this.Key] == MongoDBNull.Value)
                document.Remove(this.Key);
        }
    }
}